spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fruit?autoCommit=true&autoReconnect=true&connectionCollation=utf8mb4_general_ci&characterEncoding=UTF-8&useSSL=false&roundRobinLoadBalance=true&failOverReadOnly=false
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    #验证连接的有效性
    test-while-idle: true
    #获取连接时候验证，会影响性能
    test-on-borrow: alse
    #在连接归还到连接池时是否测试该连接
    test-on-return: false
    validation-query: SELECT 1 FROM DUAL
    #空闲连接回收的时间间隔，与test-while-idle一起使用，设置1分钟
    time-between-eviction-runs-millis: 60000
    #连接池空闲连接的有效时间 ，设置30s
    min-evictable-idle-time-millis: 30000
    initial-size: 2
    #指定连接池中最大的活跃连接数.
    max-active: 5
    #指定连接池等待连接返回的最大等待时间，毫秒单位.
    max-wait: 60000
    #指定必须保持连接的最小值
    min-idle: 2
mybatis:
  mapper-locations: classpath:mapper/*.xml,mapper/**/*.xml
  type-aliases-package: com.jzx.**.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名法
    map-underscore-to-camel-case: true